version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ria-postgres
    restart: always
    environment:
      POSTGRES_USER: ria_avtovukyp
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ria_avtovukyp_production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ria-avtovukyp
    command: bin/rails s -b 0.0.0.0 -p 3000 -e production
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: "d1ac602963ab958a988ca6da0ec491ae"
      DATABASE_HOST: db
      DATABASE_USERNAME: ria_avtovukyp
      DATABASE_PASSWORD: mysecretpassword
      DATABASE_NAME: ria_avtovukyp_production
    ports:
      - "127.0.0.1:3000:3000"
    restart: always

volumes:
  postgres_data:
